# Site settings
title: 菠菜的博客
email: 971302351@qq.com
description: > # this means to ignore newlines until "baseurl:"
  菠菜的博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://conerlius.github.io/ # the base hostname & protocol for your site
rss_url: /pages/feed.xml
author: Conerlius

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'
recent_num: 20

# Social account
#twitter: suyan404
#weibo: suyan0830
github: conerlius
#instagram: suyan404
#linkedin: suyan404

# avatar and Favicon
avatar: http://conerlius.github.io/img/avatar.jpg.png
favicon: http://conerlius.github.io/img/favicon.ico

# disqus config
disqus:
  shortname: conerlius

# google analytics config
ga:
  id: UA-148607761-1
  url: conerlius.github.io

# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
mathjax: disabled
sass:
  style: compressed

# Jekyll Plugin
# https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

